fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
    firewall:
      repo: https://github.com/puppetlabs/puppetlabs-firewall.git
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    sudo:
      repo: https://github.com/saz/puppet-sudo.git
    logrotate:
      repo: https://github.com/voxpupuli/puppet-logrotate.git
  symlinks:
    gpfs: "#{source_dir}"
