fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.11.0
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
      ref: 2.2.1
    firewall:
      repo: https://github.com/puppetlabs/puppetlabs-firewall.git
  symlinks:
    gpfs: "#{source_dir}"
